import type { Metadata } from "next";
import "./globals.css";
import AppProvider from "@/providers/AppProvider";
import MainLayout from "@/components/MainLayout";
export const metadata: Metadata = {
  title: "RWT",
  description: "Generated by create next app"
};
export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppProvider>
          <MainLayout>{children}</MainLayout>
        </AppProvider>
      </body>
    </html>
  );
}
